### ISSUE TITLE
Subset fails for different yaml style nodes

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_serialization#2]
The source yaml node should be a subset of the target node regardless of the represented style.

```yaml
# Source
constraint_region:
  primitives:
    - type: 1
      dimensions: [0.01, 0.01, 0.01]

# Target: encoded with EmitterStyle::Flow
constraint_region:
  primitives:
    - {type: 1, dimensions: [0.01, 0.01, 0.01]}
```
I suspect that this fails because the types does not match and fails [here](https://github.com/captain-yoshi/moveit_serialization/blob/master/serialization/src/yaml-cpp/node_manipulation.cpp#L80-L88).

**Comment by captain-yoshi** [comment]
Another example:
```yaml
# flow
dimensions: [0.01, 0.01, 0.01]

# block
dimensions:
  - 0.01
  - 0.01
  - 0.01
```
